NODE_TYPE_PROJECT = 'cloudify.nodes.resource_management.Project'
NODE_TYPE_ROOT = 'cloudify.nodes.Root'
NODE_TYPE_QUOTA = 'cloudify.nodes.resource_management.Quota'
NODE_TYPE_USAGE = 'cloudify.nodes.resource_management.Usage'

PROPERTY_DEPLOYMENT_ID = 'deployment_id'
PROPERTY_OPERATION_INPUTS = 'operation_inputs'
PROPERTY_PROJECT_NAME = 'project_name'
PROPERTY_RESOURCE_NAME = 'resource_name'
PROPERTY_RUNTIME_PROPERTY_NAME = 'runtime_property_name'
PROPERTY_SCOPE = 'scope'
PROPERTY_SYSTEM_NAME = 'system_name'

SCOPE_GLOBAL = 'global'
SCOPE_PROJECT = 'project'
